# Site settings
title: Nick and Cristina's Wedding
email: sam.younger@gmail.com
description: >
  This is a website for Nick and Cristina's wedding 2025
baseurl: ""
url: "http://nickandcristinawedding.com"
github_username:  samyounger

# Build settings
markdown: kramdown
theme: minima
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
  - s3_website.yml
  - README.md
sass:
  style: compressed

# Allows routes to be served without .html appended
permalink: pretty

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true